### ISSUE TITLE
storefront: content not being displayed

### ISSUE THREAD

**Issue by RiccardoLandolfo** [woocommerce/storefront#1036]
Don't know if this is a bug, but I've already ask in a forum and people do have similar problems...

I've recently created a website. Everything looks fine, but the content on a page (https://beebetter.ch/ueber-beebetter/) is not displayed correctly. I tried another template and it worked.

Also, when I navigate to the shopping cart, nothing is shown. The footer seems to overlap the content body. I just changed the text on the footer in the php-code. It seems like that just normal pages are malformed, because the shop is displayed correctly.

**Comment by GlennMartin1** [comment]
Regarding the missing Cart page, it's possible the WooCommerce default pages are not installed.

Go to **WooCommerce** > **Status** > **Tools** > **Create default WooCommerce pages**, and click **Create Pages**. That may resolve the missing Cart page.

**Comment by RiccardoLandolfo** [comment]
Thanks for your answer, @GlennMartin1. I figured it out, but now the mainpage is malformed. Have a look here: [https://beebetter.ch/](https://beebetter.ch/)

**Comment by tiagonoronha** [comment]
Hi @RiccardoLandolfo,

If you'd like to use the default Homepage template included with Storefront, you'll need to create a new page and assign the Homepage template to it. Have a look at the documentation here: https://docs.woocommerce.com/document/installation-configuration/#section-12

As for the footer, it doesn't "stick" to the bottom of the page because you don't have enough content on your site to fill the whole height of the window. I'd suggest not using a different background color in the footer and instead just use the same as the body.

Since this it not a bug, please use our support forums If you need further support: https://wordpress.org/support/theme/storefront

Thank you!
