### ISSUE TITLE
Background Image Not Responsive

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/storefront#1057]
Howdy!

Under `Appearance > Customize > Background`, if an image is selected it is not re-sized for mobile viewing.

For example, take this site: https://www.egothreadz.com/

The background image is here: 

![http://cld.wthms.co/nrb01P](http://cld.wthms.co/nrb01P+)
Screencast link: http://cld.wthms.co/nrb01P

Here's the actual image settings: 

![http://cld.wthms.co/cJbn5M](http://cld.wthms.co/cJbn5M+)
Image link: http://cld.wthms.co/cJbn5M

Here's what it looks like on mobile devices: 

![http://cld.wthms.co/t8YGSR](http://cld.wthms.co/t8YGSR+)
Image link: http://cld.wthms.co/t8YGSR

The image keeps getting larger once I scroll down the page.

The image should be static in that mobile-viewing space.

**Comment by tiagonoronha** [comment]
@zwiesman31 This a tricky issue. First of all, that's a WordPress feature, not Storefront.

This all depends on the image that's used for the background and configuration then also needs to be adjusted.

For this specific situation, instead of adding the background in the Customizer, you can do it via custom CSS:

```
body:after{
      content:"";
      position:fixed;
      top:0;
      height:100vh;
      left:0;
      right:0;
      z-index:-1;
      background: url("https://www.egothreadz.com/wp-content/uploads/2019/02/EGO-Site-Hero-NEW-3.jpg") left top;
      background-size: cover;
}
```
