### ISSUE TITLE
Assistive tech (VoiceOver) not reading hamburger menu correctly

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/storefront#1070]
As reported in #1836944-zen the expectation with VoiceOver and  collapsed hamburger menu is that tabbing through screen elements would skip the menu items, however, this is not the case i.e. menu items that exist are still read by the screen reader.

The expected behavior can be seen with the Twenty Seventeen theme.

⌘ + F5 will turn on VoiceOver. Tab around the site to listen to the descriptions

You can use Google Chrome inspect to visit the mobile view, and see the hamburger menu. Tab through to hear it speak each menu item, even when the menu remains collapsed.

This can be fixed by toggling div.handheld-navigation display on the same event that toggles the button https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element

**Comment by zuhairmahd** [comment]
Looking forward to seeing a fix for this issue

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1074

**Comment by haszari** [comment]
@tiagonoronha can you comment with info about why this was reopened? Are there problems with PR #1074 ?

**Comment by tiagonoronha** [comment]
@haszari https://github.com/woocommerce/storefront/pull/1080#issue-261516953

**Comment by haszari** [comment]
Thanks @tiagonoronha ! For posterity: the fix PR got reverted - #1081

**Comment by haszari** [comment]
Adding this to 2.5.7 - would be great to improve accessibility here (assuming we can tidy this up without risk/regressions).

**Comment by haszari** [comment]
I've retested this (with `master` branch, i.e. 2.5.7) and it's working correctly now - I think this issue was accidentally left open when the original PR was reverted.

In my testing, the navigation button `aria-expanded` attribute correctly toggles between `true`/`false`. With VoiceOver on, the the menu items are not read out when they aren't visible. 

Closing - please reopen or log a new issue if this issue is still a problem after updating to Storefront 2.5.7 (RC and release coming soon).
