### ISSUE TITLE
The use of both px and em for media queries

### ISSUE THREAD

**Issue by AlchemyUnited** [woocommerce/storefront#1108]
This isn't a bug / issue per se, but what is the mindset / advantage of fill flopping with the use of px and em for the media queries? How does something as random / arbitrary as say max-width: 66.4989378333em get used? Is there any consideration given to how these quirks (?) effect customizations?

tia -
mfs

**Comment by tiagonoronha** [comment]
The numbers are all based on a [modular scale](http://www.modularscale.com/?14,12&px&1.618&web&text).

It translates to about ~1064px. It's done this way so that the layout scales proportionately depending on the base font size.

We are aware that we use pixels in some places, and em in others.

That's something that we'd like to correct, but with hundreds of thousands of sites using Storefront, any kind of structural change can have a big impact on how those sites look and function.

This is probably something we'll address in a future major release.

**Comment by AlchemyUnited** [comment]
@tiagonoronha  - Thanks. I don't have a problem either way. But the mix & match just doesn't make any sense. Storefront is already a PITA to customize. This only adds more friction. 

How about just a simple fork and call it Storefront 2? With the only difference being the CSS. That should be maintainable (and help cut down on swearing worldwide. lol)
