### ISSUE TITLE
Making Gutenberg stylesheet conditional

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#1121]
I'm referring to the following lines of code:

https://github.com/woocommerce/storefront/blob/7f7e6be467db4779d7c4b3f170b8cbb3f58dcc21/inc/class-storefront.php#L286-L287

In instances where Gutenberg is disabled, by using a plugin/child theme with a filter, shouldn't we remove the loading of Gutenberg styles in Storefront? If blocks aren't used, there's no need to add the feature bloat on sites.

---

If required, the filters that'll be set to disable Gutenberg, include:

```
// disable for posts
add_filter('use_block_editor_for_post', '__return_false', 10);

// disable for post types
add_filter('use_block_editor_for_post_type', '__return_false', 10);
```

**Comment by tiagonoronha** [comment]
@RiaanKnoetze I've made a few changes in https://github.com/woocommerce/storefront/pull/1122 to ensure that CSS is only loaded via Gutenberg hooks.

However, this is will still load the stylesheets in the frontend since WordPress doesn't currently include a way to know if blocks are being used in a post (that's different from checking whether the block editor is enabled).

Should WordPress add a way, it will work.
