### ISSUE TITLE
Image block options left aligned in Storefront

### ISSUE THREAD

**Issue by pauljacobson** [woocommerce/storefront#1230]
Image block options are left aligned when the Storefront theme is activated.

### Steps to reproduce

1. I added an Image block to a post on my self-hosted WordPress.org site, https://pljcbsntest1.mystagingwebsite.com, with Storefront active.
2. I noticed that the options for the Image block are left aligned, [like this](https://d.pr/i/VQckP3/oXId5t3djT).
3. Switching to the Twenty Twenty theme results in the Image block options being center aligned, as I'd expect, [like this](https://d.pr/i/IakE8v/o4bqv4oj3M).

### What I expected

Image block options ought to be center aligned, regardless of the active theme, [like this](https://d.pr/i/IakE8v/o4bqv4oj3M):

![](https://d.pr/i/IakE8v/o4bqv4oj3M+)

_Screenshot direct link:_ https://d.pr/i/IakE8v/o4bqv4oj3M

Instead, they're left aligned with Storefront active, [like this](https://d.pr/i/VQckP3/oXId5t3djT):

![](https://d.pr/i/VQckP3/oXId5t3djT+)

_Screenshot direct link:_ https://d.pr/i/VQckP3/oXId5t3djT

### Observations

I reactivated Storefront, and checked the CSS that applies to the options, and noticed that when I disable `max-width: 400px;` for the `.components-placeholder__fieldset, .components-placeholder__fieldset form` element, the block options display correctly, [like this](https://d.pr/i/adF5rP/3DC2SOjND9):

![](https://d.pr/i/adF5rP/3DC2SOjND9+)

_Screenshot direct link:_ https://d.pr/i/adF5rP/3DC2SOjND9

@garymurray also did some testing, and noted the following:

>I tested it and can confirm the issue – however when you have the Twenty Twenty theme activated I can see the same `max-width: 400px;` applied to the `.components-placeholder__fieldset, .components-placeholder__fieldset form` element. 

### Browser / OS version

I was using Firefox Developer Edition, v71.0b12 on macOS 10.15.1

#### Context / Source

Internal testing of the Jetpack Beta v8.0.0 plugin.

**Comment by juliaamosova** [comment]
Thank you for reporting the issue @pauljacobson. I can reproduce it on my end.

**Storefront theme:**

![Screen Shot 2019-12-05 at 12 42 13 PM](https://user-images.githubusercontent.com/19143190/70236662-4b3e6880-175d-11ea-9f84-36ac0ca1f739.png)

**Twenty Twenty theme:**

![Screen Shot 2019-12-05 at 12 45 48 PM](https://user-images.githubusercontent.com/19143190/70236684-5396a380-175d-11ea-82ba-322e0a86cf2e.png)

I tested other blocks and it seems like the issue is indeed only with an Image block. Storefront theme below:

![image](https://user-images.githubusercontent.com/19143190/70236855-b851fe00-175d-11ea-9456-a1992646ce56.jpg)

**Comment by nielslange** [comment]
@pauljacobson & @juliaamosova I fixed this issue with https://github.com/nielslange/storefront/commit/0d4bc128357d575f368cca4af2657ec29c81df00. Feel free to test my PR and let me know if the PR needs to be updated.

**Comment by nielslange** [comment]
@pauljacobson & @juliaamosova I fixed this issue in https://github.com/woocommerce/storefront/pull/1242. Feel free to test the PR and let me know if the PR needs to be adjusted.
