### ISSUE TITLE
[2.5.4] Images no longer properly wrapping on front end

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1263]
## Describe the bug
Since 2.5.4, images that are set to wrap (i.e. left/right aligned) no longer wrap properly on the front end as they did before.

Isolating the problem (mark completed items with an [x]):
- [X] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [X] I can reproduce this bug consistently using the steps below.

## To Reproduce

**Start with 2.5.3:**
1. Create a new page
2. Insert a paragraph block with content.
3. Insert an image block.
4. Left-align the image so that paragraph wraps around the image.
5. View front end. Everything is nicely wrapped as expected.

**Upgrade to 2.5.4:**

- You will note it remains correct on the backend.
- You will note the wrapping is not working correctly on the front end.

## Screenshots
These screenshots illustrate 2.5.4.

BACKEND (which displays properly after 2.5.4):
![backend](https://user-images.githubusercontent.com/30901407/74843428-e0cbac00-52f9-11ea-9aec-8a08de5b8c8c.jpg)

FRONTEND (which does not display properly after 2.5.4):
![frontend](https://user-images.githubusercontent.com/30901407/74843464-f04af500-52f9-11ea-81b5-8198e3d7f8f4.jpg)

## Expected behavior
The frontend should display as it did with 2.5.3, wrapping properly on the frontend.

FYI 1: I'm not using WooCommerce.
FYI 2: The same bug is present with Storefront, or with the Homestore child theme.

**Comment by haszari** [comment]
Thanks for reporting this @GlennMartin1 .

I've reproduced on a test site. Images aligned right or left (float layout) now are misaligned with the top of the neighbouring paragraph block. 

Adding this to 2.5.5 as the bug was introduced in the last release.

Steps to reproduce:

1. Add an image block to a page. Resize the image so it's fairly small (e.g. 1/5th page width). 
2. Set image block `Align Left` or `Align Right`.
3. After the image block, add a paragraph block with some content. Setting a background color for the block (so you can see the edge that should align).
4. Publish and view the page on the front end. 

Expected: top of image should align with top of paragraph div (consistent with 2.5.3).

Actual: top of image is offset from paragraph.

The editor should also show a reasonably accurate preview of the front end layout.

### Screenshots
#### Editor
<img width="876" alt="Screen Shot 2020-02-20 at 11 16 10 AM" src="https://user-images.githubusercontent.com/4167300/74881579-6d499d80-53d2-11ea-8a39-3946cae07da2.png">

#### Front end - 2.5.4 (bug)
<img width="845" alt="Screen Shot 2020-02-20 at 11 09 24 AM" src="https://user-images.githubusercontent.com/4167300/74881645-90744d00-53d2-11ea-81ad-09c0d757e0d4.png">

#### Front end - 2.5.3 (correct behaviour)
<img width="860" alt="Screen Shot 2020-02-20 at 11 09 04 AM" src="https://user-images.githubusercontent.com/4167300/74881678-9c600f00-53d2-11ea-98dd-519625e83a55.png">

**Comment by nielslange** [comment]
@GlennMartin1 & @haszari I've addressed this issue in https://github.com/woocommerce/storefront/pull/1265. Feel free to look up the PR and let me know if something needs to be adjusted.

**Comment by GlennMartin1** [comment]
Works well!

Aiming for a short release cycle for 2.5.5 (hopefully)?

**Comment by haszari** [comment]
We've tagged 2.5.5 RC 1 including this fix - @GlennMartin1 feel free to grab the zip file and test it out :)

https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.5-rc.1
