### ISSUE TITLE
Product title has no margin to product image

### ISSUE THREAD

**Issue by ajgw** [woocommerce/storefront#1288]
As with Storefront 2.5.5 product titles are right below product image with no space between both. This looks awesome. Before 2.5.5 there was a margin between.
![Bildschirmfoto 2020-03-06 um 13 30 30](https://user-images.githubusercontent.com/3390880/76083899-efc78500-5fae-11ea-9aab-d2acd06bd9be.png)

**Comment by nielslange** [comment]
@ajgw Thanks for reporting this issue. I'll look into this issue in the next days.

**Comment by haszari** [comment]
Is this issue fixed by #1276 ? If this issue was introduced in 2.5.5 release it would be great to fix in 2.5.6.

**Comment by nielslange** [comment]
> Is this issue fixed by #1276 ? If this issue was introduced in 2.5.5 release it would be great to fix in 2.5.6.

I thought I had fixed this issue already. I'll look up this issue later today.

**Comment by Aljullu** [comment]
The fix for this issue will be included in Storefront 2.5.6, which is planned to be released in a couple of weeks. If you want, you can already try the Release Candidate:
https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.6-rc.1
We did a lot of internal testing, but if you find an issue, we would appreciate if you could report it.
