### ISSUE TITLE
Product images not centered on Shop page

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/storefront#1296]
## Describe the bug

If the images are smaller they are not centered:

![](https://d.pr/i/HFKJHt+)
**Image Link**: https://d.pr/i/HFKJHt+

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## Expected behavior

In previous versions of Storefront, they were centered.

**Comment by nielslange** [comment]
@SiR-DanieL I fixed this issue in https://github.com/woocommerce/storefront/pull/1297, thus, feel free to test this fix. 😉

**Comment by haszari** [comment]
I think this issue is limited to the shop page - @nielslange @SiR-DanieL can you confirm the details of where this bug occurs: page, template, shortcode, block etc.

I reproduced this on the shop page. I'm not clear on what's involved in generating this page (shortcodes, templates etc), but I didn't see the issue on the homepage template or the `All Products` block. Would be good to confirm what specific areas are affected so we can fully test the fix.

<img width="280" alt="Screen Shot 2020-03-25 at 4 45 24 PM" src="https://user-images.githubusercontent.com/4167300/77499824-0a0ec780-6eb8-11ea-99ab-329c72cc8d83.png">

**Comment by nielslange** [comment]
@haszari I've only checked the product page. (Shame on me.) 🤭
