### ISSUE TITLE
[GlobalStep - 4.2 RC1]: Icons for Reply, Edit(Pencil) and Document are not displayed on Storefront theme. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/storefront#1361]
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave -10.14.6 -Safari(v13.0.5 )

**Steps to Reproduce:**
1. Create a site using Ninja tool.
2. Add all the plugins.
3. Go to Appearance > Theme > Add New.
4. Search and activate Storefront theme.
5. Go to Posts > Add New.
6. Create a post and publish it.
7. Observe that Reply, Edit(Pencil) and Document icons are not displayed on Post comments.

**Note:** We were able to see Reply, Edit(Pencil) and Documents icons 
previously but now not able to see the icons on same site.

**Actual Result:**
Icons for Reply, Edit(Pencil) and Document are not displayed on Storefront theme. 

**Expected Result:**
Reply, Edit(Pencil) and Document icons should be displayed on Post comments.

![#26577_Icons](https://user-images.githubusercontent.com/41110392/82572705-5f0e4780-9ba2-11ea-8754-fa9fa246c9b0.png)

![#26577_No_Icons](https://user-images.githubusercontent.com/41110392/82572719-646b9200-9ba2-11ea-82de-077c3eb10211.png)

**Comment by haszari** [comment]
Thanks @tammullen  @gglobalstep :)

@gglobalstep  Can you confirm the version of Storefront you were using when you saw this bug? This issue has been fixed in [Storefront 2.5.7 RC](https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.7-rc.1): #1319 

To test Storefront 2.5.7 RC, you'll need to:

- Download the zip from GitHub here: https://github.com/woocommerce/storefront/releases/download/version%2F2.5.7-rc.1/storefront.zip
- Install that version as your theme. In wp-admin, click `Appearance > Themes`, `Add New`, `Upload Theme` then select the Storefront 2.5.7 zip file and follow the prompts to install and activate.

**Comment by nerrad** [comment]
In lieue of no response for roughly two months, I'm closing this issue (especially since it's fixed in #1319). If it pops up again a new issue can be created.
