### ISSUE TITLE
[GlobalStep - WooCommerce 4.9] Downloadable file name appears misaligned on "Order Received" and "Downloads" Page

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/storefront#1604]
## Bug Description:
Downloadable file name appears misaligned on "Order Received" and "Downloads" Page

## Environment:
Windows 10, Mac 10.15.7 (19H114).
Browser: Chrome(Version 87.0.4280.88 (64-bit)) 
               Firefox(Version 83.0)(64-bit)
               Safari: v13.1.1 (14609.2.9.1.3)
                
 
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Create a Downloadable product and Add its File Name as "supercalifraglisticexpialidociousABCDEFGHIJKLMNOPQRST".
1. From front end, add the product to cart and Proceed for checkout.
1. Complete the Payment via Card.
1. After Checkout, On "Order Received" page, Note the file name to download the file appears truncated.
1. Click on "My Account"
1. Click on "Downloads" tab
1. Observe that Downloadable "File Name" appears misaligned on "Downloads" Page 

## Actual Result:
Downloadable file name appears misaligned on "Order Received" and "Downloads" Page
 
## Expected Result:
Downloadable file name should appear properly aligned on "Order Received" and "Downloads" Page 

## Screenshots:

![#28808](https://user-images.githubusercontent.com/41110392/104473210-bc984e00-55e2-11eb-972c-d0ecff126967.png)

![#28808_2](https://user-images.githubusercontent.com/41110392/104473802-6081f980-55e3-11eb-86dd-04dfd6c89664.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
@juliaamosova it appears that the storefront examples have a sidebar whereas your test in the Twenty Twenty One is in a view without a sidebar. It's not apparent to me that this is exclusively a Storefront issue? Could this be a styling issue for the table layout produced by WooCommerce core that surfaces in narrow containers?

**Comment by juliaamosova** [comment]
>@juliaamosova it appears that the storefront examples have a sidebar whereas your test in the Twenty Twenty One is in a view without a sidebar. It's not apparent to me that this is exclusively a Storefront issue? Could this be a styling issue for the table layout produced by WooCommerce core that surfaces in narrow containers?

I am sorry for the delayed response here @nerrad! 

I went ahead and tested this a bit further. 

I installed [Options for Twenty Twenty-One](https://wordpress.org/plugins/options-for-twenty-twenty-one/) in order to get the sidebar in Twenty Twenty One theme. Note that this plugin prompts you to install another one (there will be a prompt to do that) that will allow you to actually activate the sidebar. The 2nd plugin is free for 7 days (no payment is taken) which is how I managed to test it. 

Downloads page in Twenty Twenty One theme with a sidebar looks good:

![Screen Shot 2021-03-04 at 1 54 55 PM](https://user-images.githubusercontent.com/19143190/110015756-3d75eb00-7cf2-11eb-90d5-22e1208e4ea5.png)

In a way, it does seem like the issue is specific to Storefront. However, as you mentioned on Slack it may still be core if Storefront is just inheriting the default template styles. It depends on what Storefront is overriding/keeping from core.

@claudiosanches would you please take a look and provide feedback here? Thanks!

**Comment by claudiosanches** [comment]
@nerrad This one is an issue on Storefront side, because by default Storefront removes all styles from WooCommerce core, see: https://github.com/woocommerce/storefront/blob/5a3619d4dbed265dbeab3ce64b2f9e211d7531b4/inc/woocommerce/class-storefront-woocommerce.php#L39
Also nothing related to sidebars, it's just missing a `word-break: break-all;`.

**Comment by nerrad** [comment]
Thanks for the reply (and the PR 🎉 ) @claudiosanches. I missed that filter Storefront was using. Someone from Rubik will be looking into the PR soon.

**Comment by opr** [comment]
Thanks for the report, I was able to reproduce this in Chrome, Firefox, and Safari. I've added this to our backlog to be worked on.

**Comment by nerrad** [comment]
@opr this already has a PR in #1624 that just needs reviewed.
