### ISSUE TITLE
Handheld Footer Bar Hidden on Input Focus

### ISSUE THREAD

**Issue by meirroth** [woocommerce/storefront#1611]
When focusing on the quantity input the mobile footer bar disappears. 
Whats the reasoning for this behavior?

The CSS rule that is causing this:
https://github.com/woocommerce/storefront/blob/5a3619d4dbed265dbeab3ce64b2f9e211d7531b4/assets/css/woocommerce/woocommerce.scss#L239-L244

### To Reproduce
Focus on quantity input,

### Screenshots
<img src="https://user-images.githubusercontent.com/12494197/108004943-39a65100-6fef-11eb-833a-4793af047405.png" width="50%"><img src="https://user-images.githubusercontent.com/12494197/108004952-432fb900-6fef-11eb-8a9e-7e59399baba8.png" width="50%">

**Comment by Aljullu** [comment]
> Whats the reasoning for this behavior?

The reason is so there is more available space in the screen. Most mobiles open the on-screen keyboard when an input is focused, so the available vertical space is reduced considerably.

It's true, however, that in some cases this behavior is not necessary at all, like in modern phones that have a big enough screen, or in devices with an external keyboard. So I think a middle point between completely removing or keeping it would be to move it inside a media query based on `max-height`, so something like this:

```CSS
@media screen and (max-height: 300px) {
	.sf-input-focused .storefront-handheld-footer-bar {
		display: none;
	}
}
```

This way the bar would only be hidden in devices with low vertical space. Does that sound like a good solution? Would you like to open a PR @meirroth?

**Comment by meirroth** [comment]
Yes.
Thank you @Aljullu!
