### ISSUE TITLE
Storefront cloned and built from repo won't load JS assets

### ISSUE THREAD

**Issue by clb92** [woocommerce/storefront#1707]
We use Storefront, but with some CSS breakpoint changes that can't be made in our child theme (cough #991). Therefore we pull the source from this git repository, apply a patch to one file, and run `npm install && npm run build` to build the theme.

But since version 3.6.0 we get these errors after the theme is installed, which gives us a lot of problems with the theme:
```
GET https://devmixproud.clb92.xyz/wp-content/themes/storefront/assets/js/woocommerce/header-cart.min.js?ver=3.7.0 net::ERR_ABORTED 404
GET https://devmixproud.clb92.xyz/wp-content/themes/storefront/assets/js/footer.min.js?ver=3.7.0 net::ERR_ABORTED 404
GET https://devmixproud.clb92.xyz/wp-content/themes/storefront/assets/js/skip-link-focus-fix.min.js?ver=20130115 net::ERR_ABORTED 404
GET https://devmixproud.clb92.xyz/wp-content/themes/storefront/assets/js/navigation.min.js?ver=3.7.0 net::ERR_ABORTED 404
GET https://devmixproud.clb92.xyz/wp-content/themes/storefront/assets/js/skip-link-focus-fix.min.js?ver=20130115 net::ERR_ABORTED 404
GET https://devmixproud.clb92.xyz/wp-content/themes/storefront/assets/js/woocommerce/header-cart.min.js?ver=3.7.0 net::ERR_ABORTED 404
GET https://devmixproud.clb92.xyz/wp-content/themes/storefront/assets/js/footer.min.js?ver=3.7.0 net::ERR_ABORTED 404
```

I've tried pulling just the 3.7.0 branch with this command `git clone --depth 1 --branch 3.7.0 https://github.com/woocommerce/storefront/` and building that, but it makes no difference.

If I however take the built ZIP-file from Releases, we don't get any of these problems.
Shouldn't it work when I clone the repo and compile it myself? Or am I missing a step or a recent change in the build procedure?

**EDIT:** Also, the source code archives in Releases does not contain any sass/scss. Surely, that should still be there as part of the source code?

**Comment by mikejolley** [comment]
Hi there 

I just tested a clean checkout + build to ensure there are no issues here, and from what I can see it's working correctly.

1. Checkout Trunk
2. Run `npm install && npm run build`
3. Checked asset directory — `assets/js/woocommerce/header-cart.min.js` — exists.
4. Checked for 404s on site. 

I think it must be something in your workflow. We've not seen any problems with our releases ourselves, so builds must be working.

You should:

- Check the output in the terminal during the build - did it complete? Errors? Perhaps there is a problem with the change you're making.
- Check the assets directory for the minified files. Are they there?
- How are you transferring files after the build? The minified files are excluded from source control. Ensure they are uploaded to the site.
- Could it be a caching or minification plugin causing the 404?

> Also, the source code archives in Releases does not contain any sass/scss. Surely, that should still be there as part of the source code?

We only ship built files where possible in releases. The scss files are only used by the build process.

Thanks (I am marking this closed since there doesn't appear to be a bug)

**Comment by clb92** [comment]
After abandoning this theme for a while, and coming back to it now, our problem seemed to be that some minified assets simply weren't generated during the build process.

I set up an Ubuntu 20.04 LTS VM with a fresh installation of newest NodeJS and NPM (the versions I used before were *ancient*), and the result was the same: Missing minified assets.

I've then installed specific versions of NPM (6.14.15) and NodeJS (14.18.2) as specified in `package.json`, and now it seems to build properly.

Thanks for the tips and ponters.
Merry Christmas!
