### ISSUE TITLE
Store notice does not stick to the bottom when handheld footer bar removed

### ISSUE THREAD

**Issue by rsalafy** [woocommerce/storefront#1717]
Store notice does not stick to the bottom when handheld footer bar removed, but it floats in its former place when handheld footer bar not removed.

**Comment by rsalafy** [comment]
Remove the handheld footer navigation bar using this:

https://docs.woocommerce.com/document/remove-the-handheld-navigation-bar/

**Comment by opr** [comment]
Hi @rsalafy - thanks for submitting this issue. Could you provide us with some screenshots/testing steps to reproduce this? I'm not 100% sure what you're seeing vs. what you're expecting to see.

**Comment by nerrad** [comment]
Hi @rsalafy, I'm going to go ahead and close this issue since we haven't heard from you and there's not enough info here for us to reproduce and address this. If you still have additional information and are able to answer @opr's request above - please do add a comment and if it's enough info for us to reproduce we'll reopen the issue.

**Comment by rsalafy** [comment]
I think my explanations are already clear enough.
