### ISSUE TITLE
Fractional product quantity shown as 0

### ISSUE THREAD

**Issue by olegabr** [woocommerce/storefront#2124]
https://github.com/woocommerce/storefront/blob/ee50498a7b9c1634fc01a71e85f9163cdd73a501/inc/woocommerce/storefront-woocommerce-template-functions.php#L93

If the product quantity is not an integer, like 0.5, then 0 is shown instead.

Solution: add a filter to replace the format string in plugins.

**Comment by danieldudzic** [comment]
Hi @olegabr,

We really appreciate you taking the time and creating this issue.

There is an investment of time needed by our team to consider the impact of addressing the fractional product quantity issue that you have raised. Because at this time, this does not fall into one of [the criteria "buckets"](https://github.com/woocommerce/storefront/blob/trunk/STOREFRONT_STATUS.md), we will go ahead and close it.
