### ISSUE TITLE
Revise default single product page

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#373]
Here's our current single product page in Storefront;

![current product page](https://cldup.com/S2hiwqShKy.png)

There are a couple of issues with the design as it stands;
- The sidebar will typically contain widgets that can be considered distractions on this page.
- Reviews are hidden - hiding one of the biggest sales drivers by default doesn't feel like a great idea.
- Small images - like reviews, images are a big sales driver. Generally bigger = better.

Here's a rough idea (inspector ftw) of what we could look to do with this page;

![revised product page](https://cldup.com/Ngz38g5yOL-2000x2000.png)
- The sidebar is 'replaced' with general product content that will help drive sales...
- ... which makes the main content area larger resulting in bigger images and more room for the main product description
- Reviews are visible by default
- Upsells are more prominent in the sidebar
- We can still utilise tabs for attributes and content added by extensions

A new widget region can be added specifically for product pages. They'd just appear beneath the product-focused content in the sidebar.

Overall this should make the product page more efficient in achieving it's goal - convincing visitors to click that add-to-cart button!

**Comment by BurlesonBrad** [comment]
can I volunteer to 'test' this? _email me_ 

So, what happens to the sidebar when someone's using storefront woocommerce customizer?

**Comment by jameskoster** [comment]
@BurlesonBrad 

> So, what happens to the sidebar when someone's using storefront woocommerce customizer?

We'd likely revise the extension options for the new product page

> Are the "sidebar widgets" appearing after the social share buttons?

By default, they'd appear after everything else in the 'sidebar'. But you'd easily be able to change that by hooking it in with a different priority.

**Comment by BurlesonBrad** [comment]
Ok, hold on a sec and think this through with me.....

I'm a store owner and I've properly set all my store images to be the correct size.  Now in comes 2.1 and all my images are **completely jacked up** b/c the new featured image is larger.  The Ninjas are probably gonna hunt you down b/c of the support requests.

You, me, a few other thousand people can add a priority to the end of some code. Ok. Great 
Now for the other **50,000** people who have **active** installations of Storefront? 

Did you completely kill off the tabs section? IF so, is the 'order' of the sections editable (reviews 1st | info 2nd, info 1st | info 2nd) Does you run that tab section through @bekarice and their tab manager?

**Comment by bekarice** [comment]
If all tabs are "expanded", so long as they're still output using core functions, Tab Manager should be okay 😸

**Comment by jameskoster** [comment]
@BurlesonBrad 

Regarding the images; This change will be going in a major release which of course you'll be testing in a staging environment before upgrading. As soon as you notice the images are larger you should just go to your live store, change the image dimensions in the WooCommerce settings and regenerate the thumbnails pre-emptively. Shouldn't be a problem.

> Did you completely kill off the tabs section?

No. Just moved the description/reviews _out_ of the tabbed section. The other tabs would probably be placed beneath reviews.

**Comment by BurlesonBrad** [comment]
> you'll be testing in a ........

...and while **testing** is fine, I don't reckon I articulated the concern accurately regarding the images :stuck_out_tongue_winking_eye: 

> As soon as you notice the images are larger

The *_AREA_* that you are proposing is larger.  The images **(the actual uploaded image)** ain't gonna magically become larger though. :open_mouth:   

> change the image dimensions in the WooCommerce settings

@jameskoster , every store owner can set those image dimensions to 524,876,482,284 if they decided to get a wild hair up their rump and wanted to :+1: That ain't in the least bit going to magically **make** the **actual** image dimension larger

> Shouldn't be a problem

Well, then... apparently this **problem** ain't being through all the way.  Let's stop for a sec and actually **apply** the _thinkin'_ 

Let's use @bekarice's  site as an example. They've got one of those innerwebs up on the innertubes where they sell innersprings.  Here, take a gander at a page _(for one of their badass awesome products)_ [https://www.skyverge.com/product/woocommerce-memberships/](url) Now, take a lookie at the actual image used for the featured image [https://www.skyverge.com/wp-content/uploads/2015/06/woocommerce-memberships.png](url)  It's 600x600, right?

So if you make the "area" bigger in 2.1 does @bekarice -the-store-owner also receive a magical unicorn-to-fix-images?  'Cause based on what I think I hear you saying she's gonna need one.

> Yo @bekarice -the-store-owner: Just go change your image settings back to something smaller.

Well, here's what'll happen given that new **much wider** image area: Changing the media settings is gonna make the new wider layout look more awkward than a shaved chihuahua walking backwards! I ain't got time to fire up the image editor, but take the _"new wider"_ layout, but **"keep"** the old smaller image setting size.  **It looks pretty jacked up don't it!?!?!**  Heck, for all I care you can whack that regenerate button 'till Jesus comes back, pigs fly, and my ears magically get smaller.  It still ain't gonna upsize the dimensions of @bekarice 's original image! 

As another _think-it-all-the-way-through-example_ look at this product [http://dunorthdesigns.com/product/sleeveless-chiffon-blouse-2](url) The **actual dimension**s of their  featured image is 338px.  So, **_if_** you decide to more than double the ```div``` for that area, _(which is currently cranking out about 212px)_ DuNorth is going to ....**what?**

Change the image settings so that the new wider 2.1 layout is totally wonky looking?
Go back through **every single one** their images and **RE**-upload images that are slightly more than DOUBLED in size?

Look, I :heart: 'ya.  If I could take all y'alls genius rocket ninja mad codin' skills and put it into action as to how much I appreciate y'all, I would gladly bear your children for you!  _...yeah, that's **A LOTTA LOVE!**_

But the simple reality @jameskoster is this: Could you propose a new layout for a text area? Absolutely! Can you suggest some new options for the header area? Sure! Can you simply double the div for the the featured image? **no**, Sorry.  They layout will look whacked if they modify the image settings + regenerate. (_and/or_) It ain't possible to go back through each and every store owner's images and UPscale them to the wider layout.

![sf-2p1](https://cloud.githubusercontent.com/assets/6208757/14890197/4b14d824-0d27-11e6-839a-a418a640bb43.png)

**Comment by jameskoster** [comment]
Oh @BurlesonBrad, I love your comments.

OK. I concede that if the raw image you originally uploaded is smaller than it's container in 2.1, you're gonna see some whitespace. And that could be annoying.

But should that stand in the way of making the product page a better product page going forwards? I don't really think it should. If you told a store owner that uploading new images to their site would result in an increased conversion rate across the board, I think they'd see it as a no-brainer.

Ultimately store owners should be uploading larger raw images anyway. Why?

* So that when visitors click the image the lightbox/zoom actually does something useful.
* So that they can create thumbnails of a size appropriate for retina displays.

I'm still not convinced this is a massive drawback. I mean, it's not like your images are going to *shrink* or anything. 

If this does turn out to be a massive deal (really need more input to know how big this is) we can always create a plugin to 'revert' to the old layout. No problem.

**Comment by BurlesonBrad** [comment]
Howdy @jameskoster I'm hopin' your day is going good!  
Look, I see you whackin' away at all the issues, the merges, the sass, the bugs and what-not... so I know you're busy.  **IF** you get a sec, can you shoot me the exact file that you're thinking of using for that new layout up above?  If you can't, that's cool.  

I'm making some child themes, and although I've pecked out _what-looks-like_ your layout up yonder, I want to make sure my code is matching what you're new proposed layout actually is.

Thanks Pimp!

**Comment by jameskoster** [comment]
@BurlesonBrad The layout above is just an example. The final design might not look exactly like it.

Regardless it won't be a single file that get's updated. There will be a few. I'm afraid I can't be any more specific than that because until we decide on a design I won't know exactly what files I'll be touching.

The main thing is that the sidebar will be going. If you have the WooCommerce Customiser extension you can just enable the full width product layout and you'll probably be half-way there.

**Comment by BurlesonBrad** [comment]
:hourglass: @jameskoster throw me a :meat_on_bone: bone please.  We're trying to crank out child themes :stuck_out_tongue_winking_eye:

**Comment by jameskoster** [comment]
This won't be happening for some time. 2.1 dev hasn't even begun yet. It will be a major release though so you'll have plenty of time to test everything before it goes live.

Like I said, we can always prepare a plugin to revert back to the old layout, to cover all bases.

**Comment by opportus** [comment]
@jameskoster 

> The sidebar is 'replaced' with general product content that will help drive sales...

On product page sidebar, I typically set on my stores what I call a "**Trust Block**" in a text widget. Making the thing non interactive and not distractive. I **remind** my customers the **advantages** they'd get by buying on our store. 
Eg: Delivery in 24 hours guarantee - Optional free shipping - 15 days moneyback guarentee - payment logo and partners - etc...
This is actually not a distraction but **a sale driver** and it's a technique used by many online stores.

> ... which makes the main content area larger resulting in bigger images and more room for the main product description

From the few things I understood from Brad's message 😆 , I have to say I agree with him.

> Ultimately store owners should be uploading larger raw images anyway

Of course, but it's not always possible. From a lot of hours spent trying to get best possible products images from my competitors (as they did themselves before me), I'd say the average **full** image size you'll find on online store is 800x800 when it's not 600x600 or lower. Why ? There are logical reasons to this that I won't discuss here, but all you need to know is that it's a simple matter of ressources.

For all the reasons mentioned above, I'd beg not removing the sidebar from its actual place. But I know you're an open minded person and will listen to your users so I don't worry.
Removing the sidebar and making bigger the product image... this layout wouldn't be possible from your Designer plugin ?

> Reviews are visible by default

**This**, I totally agree. There is no point discussing further about that, removing the reviews from hidden tabs is an unarguable good thing.

**Comment by jameskoster** [comment]
@opportus Totally understand, I appreciate not all widgets are distractions but would argue that most are, especially for more casual/less fastidious store owners than yourself who don't think about these things so much :) 

Just to clarify; the global widget-region would be removed, but a product-page specific widget region would be added. That'd probably display beneath the upsells in my example. So you'd still be able to add that kind of information, it'd just be easier :)

Re the images; this is tricky. A 600x600 average is actually quite good though. In Storefront core we currently display them at ~300 so there's definitely some room to increase that as long as we stick to 600 as a maximum.

I think I'll wireframe this page soon so that we can take a more grass-roots look at the possibilities.

**Comment by opportus** [comment]
Indeed, would be better testing it before all.

**Comment by jameskoster** [comment]
Here's a rough wireframe of what I have in mind;

![wireframe](https://cldup.com/HyNazJcHnH-2000x2000.png)

**Comment by BurlesonBrad** [comment]
### [http://screencast-o-matic.com/watch/cDjVoFimnf](http://screencast-o-matic.com/watch/cDjVoFimnf)
![vid-cover-git](https://cloud.githubusercontent.com/assets/6208757/17299125/98dd76ba-57d2-11e6-9ac6-461966f5c2c3.png)

**Comment by jameskoster** [comment]
How can I argue with that Frozen rendition?

OK, I'm going to leave this open but assign it to a future milestone. In the mean time, I'll probably work on a feature plugin for this idea as I still believe this would be an enhancement. We can then gauge interest and decide at a later date whether to roll it in to core or not.

Happy? xD

**Comment by opportus** [comment]
@BurlesonBrad I didn't understand what you said after you cite names of participants, but for everything else I agree excepting the fact that you clear-cut so much about the idea. If it can stay 600x600, let's give it a chance, maybe when we'll try, we'll like it a way we didn't expect ?

@jameskoster Can you make a branch of this when you have time, so users can test and say for sure what they feel about this layout ?

**Comment by jameskoster** [comment]
@opportus I think a feature plugin would serve the same purpose and give folks who like it the option to continue using the layout regardless of whether it makes it in to core or not.

Can't promise when I'll get around to creating that though as I need to focus on the 2.1 issues and other projects.

**Comment by BurlesonBrad** [comment]
Happy? Well.... honestly **no**.  I don't ever want to be "squashing" someone's vision! Enabling, empowering, educating, encouraging, are all things I want to **EXCEL** at :+1:   

I do appreciate it though @jameskoster ~ **A LOT!!** :heart:

**Comment by jameskoster** [comment]
Coming back to this issue in light of https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/

We can now create a template that is available only to products. That means we could add my proposed single product layout (and others, potentially) _as an option_.

Reckon we should include this in 2.2 @tiagonoronha ?

**Comment by BurlesonBrad** [comment]
> include this in 2.2

## I say **GO FOR IT!** 🎉 

Whatever the "final" template is, just make sure that the image size doesn't change.  Most folks running a tight, speedy, fast, correctly optimized site will be uploading product image sizes that are sized **exactly** and **specifically** what they need to be. 👍 

 _'always' & 'every'_ store owner? 🤔 nope

_**'a-significant-amount'?**_ 🤔 **YUP!**

As long as the new template's image size is the same as the previous, you'd be good to go.
However, increase the image size of the new template, and... there goes _**"backwards compatibility"**_ for all those who've uploaded the right image sizes.

_self pondering notes:
Part of me never **-EVER-** wants to squish something new.  Then there's a part of me that still thinks Storefront _(much like underscores)_ ought to be the most clean, boring, plain, solid, {insert rhetoric we've all read here}, theme in the world (again: think underscores).  
And that any changes or modifications should always and only be made via plugins, child themes, WC Extensions, template changes, hooks and filters._

Yo, store owner, you wanna different layout for Storefront? No problem: [Hire a WooExpert](https://woocommerce.com/experts/), [call Tomas](https://codeable.io), [find a plugin](https://wordpress.org/support/topic/ends-up-costing-more-than-most-premium-themes/#post-8057846), [insert a snippet](https://wordpress.org/plugins/code-snippets/), or [buy something](https://woocommerce.com/product-category/storefront-extensions/)! 👍

**Comment by jameskoster** [comment]
This would be a brand new template so backwards compatibility won't be an issue. We'd leave the current template as the default as well so existing users wouldn't notice any difference after upgrading (except for the new _optional_ product template).

I'm still not decided whether it belongs in core or a plugin, but it's nice to know we have an option of sorts now :)

**Comment by ajgw** [comment]
@jameskoster 
I did not see this template in my storefront as option. Isn't it there or am I miss something? Beside this, I have a question in case of product bundle layout: I use it for a huge amount of postcards in conjunction with [WooCommerce – Stacked Product Layout](https://wordpress.org/plugins/woocommerce-full-width-add-to-cart-forms/) and [Product Bundles – Bundle Sells](https://github.com/somewherewarm/woocommerce-product-bundles-bundle-sells/releases/) because this way customer get discount on postcards purchased in bundle.

I have change for this the css rules in that way, that bundle items are in a 3 column layout beneath product image and before add to cart button. This was required because there are more then 40 postcards in bundle.

The downside of changing css is, that all other bundled products are displayed in same way. Is there any other way to change a layout on per product level? Storefront Designer did not have such settings!

**Comment by nerrad** [comment]
While a good idea, much of this will be superseded by eventual work on FSE (block based) compatible theme where redesigns of default templates will be done.
