### ISSUE TITLE
Full Page Template Doesn't Work on Shop Page

### ISSUE THREAD

**Issue by BFTrick** [woocommerce/storefront#487]
The `Full width` template doesn't seem to work on the Shop page. It works with regular pages just not the shop page.

It it's not supposed to do anything it shouldn't be visible on the shop page - and if it is supposed to do something then that needs to be fixed.

Screencast: http://d.pr/i/njqU

Using only Storefront & WooCommerce

**Comment by jameskoster** [comment]
Yeah this has been an issue since forever, in all themes.

As you know, the shop page isn't a legitimate page. It's a placeholder that redirects to the product post type archive. So applying a page template to it in the editor is never going to work.

We could probably hide the template meta box when editing the shop page, but that isn't a silver bullet solution because it doesn't account for folks who create the shop page manually. 

If you create the shop page manually and choose a template, then come back to the page to change the template you'll find the meta box is gone - this is confusing.

I suppose the question is whether it's more confusing to have the meta box there initially but then disappear, or whether to have it permanently visible but not work.

Neither feel great to me, but seeing as the vast majority of people probably create their shop pages via the wizard then hiding the meta box is probably the lesser of two evils.

Having said that, I can already hear the "where is the page template meta box for my shop page?" support tickets.

I'm torn on this one. As a compromise, perhaps we display the meta box, but add a notice explaining why it doesn't work, with a link to docs explaining further. That's something we should do in WooCommerce core though.

**Comment by BFTrick** [comment]
> As a compromise, perhaps we display the meta box, but add a notice explaining why it doesn't work, with a link to docs explaining further. That's something we should do in WooCommerce core though.

Love this idea. I've moved this over to the WooCommerce repo.
