### ISSUE TITLE
Footer Rows

### ISSUE THREAD

**Issue by opportus** [woocommerce/storefront#492]
There are many kind of widgets that one can wish to add in a footer, especially on ecommerces. In this regard, the actual footer layout is very limited.

So what about adding new **Top Footer** widget regions, which would bring necessary flexibility to the footer and would better suit to general uses anyway ?

This screenshot should describe well enough what I mean...

![gsuite-footer](https://cloud.githubusercontent.com/assets/11618989/19204284/40808234-8cdc-11e6-8622-95b80791b5ae.png)

**EDIT**

A new flexible and extensible approach is preferable by making use of a new filter hook:

``` php
apply_filters( 'storefront_footer_widget_rows', $n );
```

After its implementation, we can get the exact same layout as on the screenshot above.

**Comment by jameskoster** [comment]
Hmm, I'm not sure if this is overkill. We already have [this plugin](https://en-gb.wordpress.org/plugins/storefront-footer-bar/) which basically does the same thing.

Any thoughts @tiagonoronha ?

**Comment by opportus** [comment]
I'd see [this plugin](https://en-gb.wordpress.org/plugins/storefront-footer-bar/screenshots/) as a nice complement to the "footer" and "top footer" widget regions, not a replacement since it doesn't really allow us to **add** widgets where we need them...

**Comment by jameskoster** [comment]
> it doesn't really allow us to add widgets where we need them and layered the way we need them...

Could you give me an example of what you need specifically? It seems to do exactly the same thing to me but I might be missing something.

**Comment by opportus** [comment]
> It seems to do exactly the same thing to me but I might be missing something.

From what I understand from the plugin's description, you can add only one widget.

> Could you give me an example of what you need specifically?

Due to my poor english vocabulary, I don't think I can describe it better than with the screenshot in the OP, but I can try:

In the actual footer, we have **only one level**. When you want to add more widgets in a different raw (which most ecommerces do) by underlying those widgets in the same column as upper widgets, this will result in a poor visual layout. We don't necessarily want the same amount of columns in the different raws.
With my solution, you can set your own amount of columns for the top footer raw and furthermore, a separator is added which simply make now possible adding widgets in different raws and gives richer footer layout possibilities.
The main problem with the actual implementation is that it doesn't give flexibility to add a footer raw due to the unique amount of columns and the missing separator. In most cases, this makes the footer limit number of widgets equal to **4** and **this** is "underkill". :P

**Comment by jameskoster** [comment]
Right, I get you now ;)

This _does_ feel like quite a big feature though and I'm not sure if it belongs in core or in something like Powerpack. I know a lot of bigger eCommerce sites have large footers like this, but for smaller shops it's overkill. Core must always be lean and only offer essential features.

Keen to hear @tiagonoronha's thoughts on this.

**Comment by tiagonoronha** [comment]
I agree with @jameskoster on this. Storefront core should stay as simple and lean as possible.

The fact that you can easily add the functionality that you described to any Storefront site proves that we are on the right track - an intuitive & flexible theme that is the perfect platform for your WooCommerce projects.

@opportus feel free to submit a plugin to WordPress.org with this functionality. :)

**Comment by opportus** [comment]
> Core must always be lean and only offer essential features.

You might know by now that I think the same :P

But where I disagree is that it's for "big ecommerce". All ecommerces may at least include newsletter widgets and social links to their sites... And things like FB Page plugin, search bar and much more can also be included in top footer. It seems to me like a **essential** feature that **should** be included in core... just my 2P !

**Comment by opportus** [comment]
As a sidenote, it represent just a few lines of code that integrate perfectly with the original approach. I don't get as it can turn Storefront into **unintuitive** and **unflexible** project. It does actually the opposite...

**Comment by jameskoster** [comment]
> And things like FB Page plugin, search bar and much more can also be included in top footer

The thing is, they can be easily added to the current footer as well. You don't _need_ the additional row for this.

Another reason for this to be a separate plugin; it might sometimes be desirable to add _even more_ rows. A footer manager plugin (multiple rows, custom columns (more than 4)) could actually be a very interesting idea.

**Comment by opportus** [comment]
> The thing is, they can be easily added to the current footer as well. You don't need the additional row for this.

We **do** need it in **most** cases, as I tried to explain above. That's why adding just 1 raw should be a minimum.

> A footer manager plugin (multiple rows, custom columns (more than 4)) could actually be a very interesting idea.

+1

**Comment by emzo** [comment]
> A footer manager plugin (multiple rows, custom columns (more than 4)) could actually be a very interesting idea.

Could work in a similar fashion to the the [Storefront Mage Menus extension](https://www.youtube.com/watch?v=KAh8FDIqOfs&feature=youtu.be&t=89), where you can add any WordPress widget and put them in different rows/columns and resize them.

Would be a cool addition to Storefront Powerpack and would complement the existing [header layout option](https://youtu.be/cLy-x4DCyko?t=189) very well.

**Comment by opportus** [comment]
I don't want to appear stubborn or something, but I want to contribute to make Storefront even better for everydody. Just this diserves I fight for my convictions and take the risk to appear as an idiot...

From my user experience of Storefront, having built some ecommerces from it for my customers and myself, I can guarantee that the proposed feature would be suited for big majority of cases and is actually much more **essential** than for exemple the header sidebar which I've personally never had to use...

Now, that would be not really fair if tomorrow, you propose this **basic** feature that everybody needs, as a premium plugin, furthermore, putting myself in the position where I should consider buying this for my next sites while I'm the one who brought it on the table, in the name of my customers... Think about it.
Don't make **premium** plugins from your user contributions.

Also, I will never believe that these 12 new lines of PHP code represent a "heavy feature" and will make Storefront "not lean", that it's for "big ecommerces", and will contribute to make it "unintuitive and unflexible" while this feature would actually represent all the exact opposites !

@jameskoster, @tiagonoronha, please, do not get me wrong, I have a big respect for both of you, the Automattic/WooCommerce team in general, and your awesome projects - which is the reason why I'm stubborning here. ;)
I believe passionate debates are a good thing.

**Comment by jameskoster** [comment]
@opportus it's not so much the code volume which is of course quite small like you say, more how this meshes with the overall Storefront philosophy. 

Having an extra row of footer widgets seems like a small feature but could potentially grow like we said before. I can definitely see people asking for more rows and more detailed management if we were to add this. Where do we draw the line on what's in core and what isn't?

That's why I suggested a separate plugin which could of course be free and separate from Powerpack. It can then grow and be as big / complex / feature-rich as necessary which is something we have to be very mindful of in core.

To me this still _feels_ like over and above what a typical Storefront user requires. Clearly you have a lot of experience and think otherwise which is why I haven't closed this issue out yet. 

Ultimately I'm waiting for feedback from other store owners before making a definitive decision here. It's a 2.2 item any way so no big rush.

In case it gets lost in the replies, I really appreciate your effort and stubbornness! I know you want to make Storefront better. We're definitely united in our overall goal! xD

**Comment by BurlesonBrad** [comment]
@opportus ❤️ 'ya: but ✋ Debating w/ the people who hold the keys is sometimes pointless.  That's not the case here, since they are obviously willing to give constructive feedback ~ which is 👍 **GREAT** 👍 

But 👀 watch 👀 
The footer bar needs to be **REMOVED** & made into a plugin.  A 'smart' plugin with Customizer integration that says, 

> "Yo.  If there's nothing in the cart, then displaying the cart icon which leads to an empty cart page is completely stupid, pointless, and psychologically useless. Let's remove that cart button and expand the div only adding & displaying the button when a customer actually **has** ~indeed~ placed something in their cart." 

_or a simple toggle button which prompts_ [ ] ```Only show cart icon when items have been added?``` 

----------------
When showing pricing for shipping on the cart page, visually displaying & showing customers a number and putting that number into their eyeballs and their head **BEFORE** prompting and asking for their **actual** location is _(again)_ completely stupid, pointless, and psychologically useless.  It's like saying 

> "Here's  the price for shipping.  Oh wait, now that you've seen that price, you'll need to scroll down the page and put in your **REAL** location to get the correct shipping options."

But people don't think that way.  That's not how the human brain psychologically works.  You should **NEVER** see a price _**first**_ and then _**lower down the page**_ have an input field prompting the user to see the _**Correct**_ price for shipping.  You've already planted ```$XX.xx``` in their head, & now you have to gamble/ hope/ pray/ wish/ that they'll scroll down _(past the prices that they just saw)_ to find the prompt which will give them the **correct** ```$XX.xx``` shipping amounts.

So.... when I'm done firing up USPS shipping, I take the cart page's template and I redo it so that the prompt for location appears first, and then the shipping prices appear below that. 

🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 


Ok, So, this is Github.  And bazillions of people use it to learn code ~ 👋 _**HI!**_ ~ report code errors, submit pull request, and things like that.  

Listen to @mikejolley & @tiagonoronha when they say:

# MAKE IT A PLUGIN

Dude, lemme say this again @opportus : ❤️ 'ya 👍 Your code is rock solid and awesome 👍 

Some things go into the core of something **_(WP, a theme, a plugin...... my effing Windows Laptop)_** 
Some things get in that you think are good. Some things get in that you think are bad.
Some things get into WP that @mikejolley thinks are good. Sometimes he submits a trac issue and it doesn't get anywhere.  Over the last 4 or 5 years, I've watched both happen. 
Same goes for @tiagonoronha . 
From a psychological sales point-of-view, there's shit I like, don't like, & I have to figure out how to fix them.  Either by stalking @jameskoster 's [gists](https://gist.github.com/jameskoster/fe69d1004d6776fa300ed9d0ed914c07) so that I can figure out _how-to-fix_ this Storefront footer bar issue, or rearranging the template's parts and pieces on the ```/cart``` page.

The goal here is for me to help you understand not just how this process works, or "who has the keys", or "what" and "why" people do & don't put stuff (good or bad) into the core of something, but rather to help you understand one simple thing:
They said make it a plugin. Make it a plugin. **Carry on being awesome.**

Your passion is steadfast and your resolve is apparent! 
![storefront-github-492](https://cloud.githubusercontent.com/assets/6208757/19314953/90594dee-9061-11e6-9c90-3d22ebde733e.png)
# Aim your passionate resolve in the **right** direction

**Comment by opportus** [comment]
Hi @jameskoster, @tiagonoronha, @BurlesonBrad.

Brad, thank you for your feedback, I really enjoy your comments dude. xD
You can be sure I've not missed your great suggestion: "**Aims your passionate resolve in the right direction**"...

So, following Brad's suggestion, allow me to approach the problem from the right direction.

It's nice to hear that Storefront phylosophy is to keep it lean and all, and somehow follows the KISS approach. That is great. The thing is that the concept is a little abstract and can drive one to consider it differently than another.
So let's focus on the code, where it's all much more concrete and clear, which is the reason why I prefer coding than listening and taking part into endless politic debates.

In Storefront 2.1.4, we have this:

```php
		public function widgets_init() {
			$sidebar_args['sidebar'] = array(
				'name'          => __( 'Sidebar', 'storefront' ),
				'id'            => 'sidebar-1',
				'description'   => ''
			);

			$sidebar_args['header'] = array(
				'name'        => __( 'Below Header', 'storefront' ),
				'id'          => 'header-1',
				'description' => __( 'Widgets added to this region will appear beneath the header and above the main content.', 'storefront' ),
			);

			$footer_widget_regions = apply_filters( 'storefront_footer_widget_regions', 4 );

			for ( $i = 1; $i <= intval( $footer_widget_regions ); $i++ ) {
				$footer = sprintf( 'footer_%d', $i );

				$sidebar_args[ $footer ] = array(
					'name'        => sprintf( __( 'Footer %d', 'storefront' ), $i ),
					'id'          => sprintf( 'footer-%d', $i ),
					'description' => sprintf( __( 'Widgetized Footer Region %d.', 'storefront' ), $i )
				);
			}

			foreach ( $sidebar_args as $sidebar => $args ) {
				$widget_tags = array(
					'before_widget' => '<div id="%1$s" class="widget %2$s">',
					'after_widget'  => '</div>',
					'before_title'  => '<span class="gamma widget-title">',
					'after_title'   => '</span>'
				);

				/**
				 * Dynamically generated filter hooks. Allow changing widget wrapper and title tags. See the list below.
				 *
				 * 'storefront_header_widget_tags'
				 * 'storefront_sidebar_widget_tags'
				 *
				 * storefront_footer_1_widget_tags
				 * storefront_footer_2_widget_tags
				 * storefront_footer_3_widget_tags
				 * storefront_footer_4_widget_tags
				 */
				$filter_hook = sprintf( 'storefront_%s_widget_tags', $sidebar );
				$widget_tags = apply_filters( $filter_hook, $widget_tags );

				if ( is_array( $widget_tags ) ) {
					register_sidebar( $args + $widget_tags );
				}
         }
			
```

```php
	function storefront_footer_widgets() {
		if ( is_active_sidebar( 'footer-4' ) ) {
			$widget_columns = apply_filters( 'storefront_footer_widget_regions', 4 );
		} elseif ( is_active_sidebar( 'footer-3' ) ) {
			$widget_columns = apply_filters( 'storefront_footer_widget_regions', 3 );
		} elseif ( is_active_sidebar( 'footer-2' ) ) {
			$widget_columns = apply_filters( 'storefront_footer_widget_regions', 2 );
		} elseif ( is_active_sidebar( 'footer-1' ) ) {
			$widget_columns = apply_filters( 'storefront_footer_widget_regions', 1 );
		} else {
			$widget_columns = apply_filters( 'storefront_footer_widget_regions', 0 );
		}

		if ( $widget_columns > 0 ) : ?>

			<div class="footer-widgets col-<?php echo intval( $widget_columns ); ?> fix">

				<?php
				$i = 0;
				while ( $i < $widget_columns ) : $i++;
					if ( is_active_sidebar( 'footer-' . $i ) ) : ?>

						<div class="block footer-widget-<?php echo intval( $i ); ?>">
							<?php dynamic_sidebar( 'footer-' . intval( $i ) ); ?>
						</div>

					<?php endif;
				endwhile; ?>

			</div><!-- /.footer-widgets  -->

		<?php endif;
	}
```

Please **note**, there is an **existing** filter for widget **columns** or "region" if you prefer...

```php
$footer_widget_regions = apply_filters( 'storefront_footer_widget_regions', 4 );
```

James, for exploiting this filter or **functionality**, you had to make a loop in each of both functions above.
You'd agree that it would be strange to implement such a simple, basic, lean, and **necessary** functionality into a plugin right ?

Now, would you still consider against Storefront phylosophy, the implemention of a filter for **rows**...
```php
$footer_widget_rows = apply_filters( 'storefront_footer_widget_rows', 1 );
```
My new approach is exactly the same as you have took with **columns** - 1 filter and 1 loop in each file.
I'd still like to point you that this filter would actually be **much more needed** than the "region" filter...

> Having an extra row of footer widgets seems like a small feature but could potentially grow like we said before. I can definitely see people asking for more rows and more detailed management if we were to add this. Where do we draw the line on what's in core and what isn't?

The good news is that now, it will be people's matters and **possibility** to draw the line on the rows limit.
Also, you can now use PowerPack (thanks to the proposed filter) to allow the same people to customize further on the top of that....

Wouldn't this make everybody happy ?

Here is the proposed code:

```php
		public function widgets_init() {
			$sidebar_args['sidebar'] = array(
				'name'          => __( 'Sidebar', 'storefront' ),
				'id'            => 'sidebar-1',
				'description'   => ''
			);
			
			$sidebar_args['header'] = array(
				'name'        => __( 'Below Header', 'storefront' ),
				'id'          => 'header-1',
				'description' => __( 'Widgets added to this region will appear beneath the header and above the main content.', 'storefront' ),
			);


			$footer_widget_rows    = intval( apply_filters( 'storefront_footer_widget_rows', 2 ) );
			$footer_widget_regions = intval( apply_filters( 'storefront_footer_widget_regions', 4 ) );

			for ( $row = 1; $row <= $footer_widget_rows; $row++ ) {
				for ( $region = 1; $region <= $footer_widget_regions; $region++ ) {
					$footer = sprintf( 'footer_%1$d_%2$d', $row, $region );

					$sidebar_args[ $footer ] = array(
						'name'        => sprintf( __( 'Footer Row%1$d Region%2$d', 'storefront' ), $row, $region ),
						'id'          => sprintf( 'footer-%1$d-%2$d', $row, $region ),
						'description' => sprintf( __( 'Widgetized Footer Row %1$d - Region %2$d.', 'storefront' ), $row, $region )
					);
				}
			}

			foreach ( $sidebar_args as $sidebar => $args ) {
				$widget_tags = array(
					'before_widget' => '<div id="%1$s" class="widget %2$s">',
					'after_widget'  => '</div>',
					'before_title'  => '<span class="gamma widget-title">',
					'after_title'   => '</span>'
				);

				/**
				 * Dynamically generated filter hooks. Allow changing widget wrapper and title tags. See the list below.
				 *
				 * 'storefront_header_widget_tags'
				 * 'storefront_sidebar_widget_tags'
				 *
				 * 'storefront_footer_1_1_widget_tags'
				 * 'storefront_footer_1_2_widget_tags'
				 * 'storefront_footer_1_3_widget_tags'
				 * 'storefront_footer_1_4_widget_tags'
				 * 
				 * 'storefront_footer_2_1_widget_tags'
				 * 'storefront_footer_2_2_widget_tags'
				 * 'storefront_footer_2_3_widget_tags'
				 * 'storefront_footer_2_4_widget_tags'
				 *
				 * And so on...
				 */
				$filter_hook = sprintf( 'storefront_%s_widget_tags', $sidebar );
				$widget_tags = apply_filters( $filter_hook, $widget_tags );

				if ( is_array( $widget_tags ) ) {
					register_sidebar( $args + $widget_tags );
				}
			}
		}
```

```php
	function storefront_footer_widgets() {
		$footer_widget_rows    = intval( apply_filters( 'storefront_aggregator_footer_rows', 2 ) );
		$footer_widget_regions = intval( apply_filters( 'storefront_aggregator_footer_regions', 4 ) );

		for ( $row = 1; $row <= $footer_widget_rows; $row++ ) {
			for ( $region = 4; 0 < $region; $region-- ) {
				if ( is_active_sidebar( 'footer-' . $row . '-' . $region ) ) {
					$widget_columns = $region;

					break;
				}
			}

			if ( $widget_columns > 0 ) : ?>
				<div class="footer-widgets row-<?php echo strval( $row ); ?> col-<?php echo strval( $widget_columns ); ?> fix">

					<?php
					$i = 0;
					while ( $i < $widget_columns ) : $i++;
						if ( is_active_sidebar( 'footer-' . $row . '-' . $i ) ) : ?>

							<div class="block footer-widget-<?php echo strval( $i ); ?>">
								<?php dynamic_sidebar( 'footer-' . strval( $row ) . '-' . strval( $i ) ); ?>
							</div>

						<?php endif;
					endwhile; ?>

				</div><!-- /.footer-widgets -->

			<?php endif;
		}
	}
```

**Comment by jameskoster** [comment]
@opportus sorry for the delay getting back to you. OK, this time you nailed it :) I like that this solution keeps the feature out of core, but makes it possible via a very simple customisation. This is exactly what Storefront core should be doing :)

Let's add this to 2.2.
