### ISSUE TITLE
Missing padding around error message

### ISSUE THREAD

**Issue by kadimi** [woocommerce/storefront#502]
![](http://i.imgur.com/QcKCuXp.png)

**Comment by jameskoster** [comment]
This is an issue in Subscriptions. The plugin should use the woocommerce notice class for this message. I'll open an issue there :)

**Comment by kadimi** [comment]
Thanks!

**Comment by thenbrent** [comment]
Hey @jameskoster. Although Subscriptions is outputting the notice displayed here, the issue is the same for the "no payment methods" notices output by WC core.

This is because WC core also only returns strings without any HTML on the `woocommerce_no_available_payment_methods_message ` filter:

* https://github.com/woocommerce/woocommerce/blob/dec792b731dbbea6d34aa3ddcd6a3bf05bf43077/templates/checkout/payment.php#L35
* https://github.com/woocommerce/woocommerce/blob/dec792b731dbbea6d34aa3ddcd6a3bf05bf43077/templates/checkout/form-pay.php#L81

Here's a screenshot of a notice with storefront when no payment gateways are enabled and the Subscriptions plugin is disabled: https://cloudup.com/c2-Dd9q_XFt

**Comment by jameskoster** [comment]
Ah, I see. Core should still be adding a class imo. Will open an issue there xD
