### ISSUE TITLE
Blog page Logo has a H1 applied to it - why?

### ISSUE THREAD

**Issue by joelwills** [woocommerce/storefront#508]
In Storefront (and as a result child themes), this function:

https://github.com/woocommerce/storefront/blob/master/inc/storefront-template-functions.php#L178

Is adding a 

`<h1 class="logo">`

to the logo image on the blog `is_home()` page only. 

Is there a reason for this? Other pages do not have this h1 class applied, just the blog page.

Seems unnecessary and can affect styling.

Thanks!

Note: 496100-zd-woothemes

**Comment by opportus** [comment]
Hi @joelwills,

This has been discused in this topic #439.

But to resume a bit here, the reason behind that is related to the document outline.
On the posts page you have multiple posts with their titles wrapped in `<h2>` tags.
Since a page also require 1 `<h1>` title, it can be only the blog name, as in categories, it's the category's title... Furthermore it makes total sense (at least to me) to have your blog's name as `<h1>` on the blog page...

If you see inconvenients to this approach, thanks for sharing :)

**Comment by jameskoster** [comment]
To add to this - while putting an `img` alone inside a `h1` is a little questionable, there does seem to be enough evidence to suggest that the `alt` attribute on the `img` or the `title` on the `a` carry a _similar_ weight to plain text. While we can't control the latter, the former is in the control of the user which makes this worthwhile imo.

**Comment by joelwills** [comment]
Thanks for explaining @opportus and @jameskoster !

**Comment by jameskoster** [comment]
No problemo!
