### ISSUE TITLE
Handheld Menu: max height issue

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#547]
I had a user in chat today say that on mobile the handheld menu was making items disappear.

The issue is the max-height for the handheld menu:
https://github.com/woocommerce/storefront/blob/ccefc2687edc9fedf9ee21e9639dea29e6f69a97/assets/sass/base/_base.scss#L1200

Once you have over about 30 items in the navigation, the rest just disappear because of the max-height set.

Some people do need a lot of menu items, so I can see a good case for us removing the limit.

**Comment by jameskoster** [comment]
We use `max-height` is because you cannot css animate `height` from `0` to `auto`. 

I think the animation is important visual feedback when the menu button is clicked so I'd like to keep that. Changing the max-height value is a very small css snippet. Given the custom css control now exists in the Customizer do you think it's reasonable to ask folks to use this?

Alternatively we could use js to animate this but I'd rather not :(

**Comment by mikeyarce** [comment]
Thanks @jameskoster - your argument wins in this case :)  We should document this somewhere in case other people run into the max-height issue.
