### ISSUE TITLE
Add support for WooCommerce brands

### ISSUE THREAD

**Issue by dwainm** [woocommerce/storefront#627]
Add support for WooCommerce brands within storefront to show the brand archive with the description and title.

Original issue: https://github.com/woocommerce/woocommerce-brands/issues/82

**Comment by jameskoster** [comment]
Designs for the Brands integration can be found [here](https://cloudup.com/c5wszle3RFk).

Notes on the design;

* The homepage section will be custom but we can leverage the shortcode. Brand logos should have a max-height. 
* On the product page the brand logo should link to the brand page.
* For the A-Z shortcode, as you scroll the A-S selector should stick to the top of the window. This way we can do without the nasty "Back to top" links.
* Widgets are fine, but when a count is visible for the brand list the style should match product category counts etc. If the brand logos widget is used the images should be aligned left rather than centrally like on the homepage.
