### ISSUE TITLE
Unable to scroll to place order button with long payment method description

### ISSUE THREAD

**Issue by gedex** [woocommerce/storefront#637]
I just set up a test store on WPCOM and use Storefront (2.2.4). Currently, there's a bug in Stripe where payment method description gets concatenated. However, with this long description, I'm not able to scroll to click the place order button. Here's the recording of it:

![storefront-issue](https://user-images.githubusercontent.com/78313/28812435-f967954a-76be-11e7-9711-d0f8b007c463.gif)

/cc @jameskoster as we had talk about this before

**Comment by tiagonoronha** [comment]
@gedex what do I need to do to replicate this issue? 

I tried different methods and no mater how long the description is, scrolling still works.

**Comment by gedex** [comment]
@tiagonoronha 

This is reproducible on my test site:

* Use incognito to open https://akeda-test-at-01.blog/
* Add one product on that shop page to the cart
* Go to the checkout page
* Scroll to the bottom of the page
* Choose **Credit Cart (Stripe)**
* Scroll up a bit

The steps at checkout page seem intermittent, so here's a way to reproduce it consistently:

![storefront-scroll-issue](https://user-images.githubusercontent.com/78313/28904477-6fa40884-7835-11e7-96e8-d45b6b1ad75b.gif)

I haven't tested this locally with `master` branch.

**Comment by mikeyarce** [comment]
I wasn't able to reproduce this on my own site - I wonder if the height of the screen has to be a certain size for this to happen?

**Comment by gedex** [comment]
I'm not sure. My window size: 1920px x 1173px.

**Comment by mikeyarce** [comment]
I can reproduce this on your test site, when my browser is set to 80% size (probably because I'm on a 13'' Macbook pro and you have a 15'' macbook pro?

I can't reproduce this on my own site.

@jameskoster what are your thoughts on removing this feature entirely?  My reasoning is that it feels a bit unexpected when it's there - I have always preferred things not moving around.

**Comment by gedex** [comment]
> and you have a 15'' macbook pro?

Correct. I'm using 15% MBP.

**Comment by jameskoster** [comment]
> @jameskoster what are your thoughts on removing this feature entirely? My reasoning is that it feels a bit unexpected when it's there - I have always preferred things not moving around.

I don't know... I still believe having the purchase button permanently visible is a useful feature. Maybe we could simplify it so that only the purchase button sticks, rather than the entire order summary? That would reduce the scope for quirks like this dramatically.

Of course we could just remove it entirely, but we'd need a feature plugin to add the functionality back in if we did so. 

What do you think @tiagonoronha ?

**Comment by tiagonoronha** [comment]
@jameskoster I think of it as fluff, I wouldn't be against removing it a putting into a feature plugin.

**Comment by jameskoster** [comment]
Let's remove it.

**Comment by RiaanKnoetze** [comment]
@jameskoster @tiagonoronha - any news on a release date for 2.3.0?

**Comment by tiagonoronha** [comment]
@RiaanKnoetze 2.2.6 will go out this week.

**Comment by nathanhere** [comment]
Lost a customer today because of this. CSS fix that worked for me:
`.woocommerce-checkout-review-order.payment-fixed {
    height: 90% !important;
    overflow-y: scroll !important
}`

**Comment by jameskoster** [comment]
Sorry to hear that @nathanhere. A better fix; `wp_dequeue_script( 'storefront-sticky-payment' );`.
