### ISSUE TITLE
Where did Main Image width and Thumbnail width go?

### ISSUE THREAD

**Issue by geeklore** [woocommerce/storefront#764]
When using the Customizer and editing product images (**Customizing -> WooCommerce -> Product Images**) it used to look like this.

![see screen shot](http://cld.wthms.co/8Euz1V+)
Link: http://cld.wthms.co/8Euz1V

Now it looks like this.

![see screen shot](http://cld.wthms.co/w2xL46+)
Link: http://cld.wthms.co/w2xL46

If you try and go to ** WooCommerce > Settings > Products** this message is shown.

> "Looking for the product display options? They can now be found in the Customizer." 

Where did these two options go?

![see screen shot](http://cld.wthms.co/wZ8jT+)
Link: http://cld.wthms.co/wZ8jT

**Comment by GlennMartin1** [comment]
These sizing options are only shown of your theme does not declare the size. 

Best practice is for the theme to declare the size, which then removes the purpose of those options. 

If you had those options in the Customizer, then they disappeared, it is because you've updated your theme, and your theme now declares the size. 

That's a good thing - congratulations!

**Comment by tiagonoronha** [comment]
What @GlennMartin1 said.

If for any reason you need to change the default sizes, you can filter the values:

https://github.com/woocommerce/storefront/blob/master/inc/class-storefront.php#L117-L127

**Comment by geeklore** [comment]
Thanks! Of course it's right [here](https://woocommerce.wordpress.com/2017/12/11/wc-3-3-image-size-improvements/).

I missed this part when I skimmed the post.

 > With WooCommerce 3.3 theme authors can now declare image sizes via the `add_theme_support` function. Declaring image sizes this way will take priority over any other settings and also hide the image settings section in the admin area.

Cheers!
