### ISSUE TITLE
Sticky Add-to-Cart on product without price or out-of-stock

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#866]
Activate Storefront with _Sticky Add-to-Cart_ turned on in Customizer.

Go to a product that does **not** have a price assigned.

After scrolling down, the _Sticky Add-to-Cart_ pane appears, which has a "Read More" button. That button should not exist; it simply points to the same product, which is meaningless.

EDIT: exact same issue if the unit is out-of-stock.

**Comment by tiagonoronha** [comment]
The button is coming from WooCommerce directly, we're not doing any modifications to it to ensure that this feature is super compatible with extensions.

But I do agree that this is not the most desirable output, so I'm leaving this issue open.

**Comment by kirpi-it** [comment]
Yes Tiago. 
All I can see is that WooCommerce itself hides the button from the product page when the product is out of stock. If I understand right, WooCommerce itself funnily lets the same button (from the visual and functional, not necessarily technical, point of view) show in this ex-plugin which is now part of WooCommerce.
And we all agree that this behaviour should be amended.

In order to help the final customers of our shops *now* (which should be the main aim of the whole WooCommerce thing), while we wait for some expert to solve the issue, is there anybody please who know how a hacky line could be written to provisionally hide the button when the product is out of stock?
I guess it should be something in "if x out of stock hide y" but I cannot go further myself, sorry. 

Thanks!

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1101
