### ISSUE TITLE
WhatsApp icons not working

### ISSUE THREAD

**Issue by naferok1** [woocommerce/storefront#875]
Font Awesome WhatsApp icons not working on 2.3.1

f098, f232

**Comment by Reijo83** [comment]
On my page Yotube and Facebook icons not working

**Comment by tiagonoronha** [comment]
@naferok1 @Reijo83 what are you using to display the icons?

**Comment by naferok1** [comment]
I have a WhatsApp icon in the mobile menu, where the shopping cart. 
Before 2.3.0 everything worked fine

**Comment by naferok1** [comment]
@tiagonoronha

**Comment by Reijo83** [comment]
I have a Youtube icon  in products description links and Facebook icon is in footer link.

**Comment by tiagonoronha** [comment]
By default Storefront doesn't display social links in the footer and/or mobile menu. 

Since Font Awesome 5, brand icons are not included in the Font. There's a separate font for that.

Use a plugin like Better Font Awesome to get this functionality back: https://wordpress.org/plugins/better-font-awesome/
